Feature/billing reports
simpleman19/acmeDSTS pull request #40
Opened 2018-06-23 06:24 UTC by dee-dee-raye

This really does work except for getting the price quote which breaks it. I believe this page itself is fine.  I tested it with a regular old BigDecimal and everything went well. I got printing to work too. The company performance report was a great example to work from!

2018-06-23 14:00 UTC, simpleman19 requested changes
Also I am not seeing a report for any customer other than customer one but it may be fixed with the uuid change

2018-06-23 14:00 UTC, simpleman19 commented on src/acme/ui/ReportsPanel.java
> +                !t.isBillToSender() && t.getDeliveryCustomer().getName().equals(customerName))
Can you use UUID to determine if the customer is the same instead of name?

2018-06-23 16:31 UTC, dee-dee-raye commented
I could see all the customers last night. I walked through it just now and it's acting like there is only one ticket.

2018-06-23 16:48 UTC, dee-dee-raye commented
It's working again for me. I don't know what changed. I just switched back to the branch and killed my db and reseeded it a couple of times.

2018-06-23 16:52 UTC, simpleman19 commented
I just ran it again and it appears to be working

2018-06-24 20:19 UTC, simpleman19 approved these changes

2018-06-24 20:19 UTC, merged